"""empty message

Revision ID: 873bc504f7d8
Revises: 
Create Date: 2022-11-08 09:29:08.498174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '873bc504f7d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comrade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('design', sa.String(), nullable=False),
    sa.Column('sub_design', sa.String(), nullable=True),
    sa.Column('cut', sa.Boolean(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('dye', sa.String(), nullable=True),
    sa.Column('dye_gradient', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal')
    op.drop_table('comrade')
    # ### end Alembic commands ###
